### ISSUE TITLE
Purpeille armor and tools disappear after death

### ISSUE THREAD

**Issue by redstonekasi** [acikek/purpeille#10]
I've had this happen to me and my friend twice now so I figure it must be a bug.
The first time I died in the void, everything except my armor was lost.
When my friend died in the nether just now, we couldn't find his armor and sword anywhere and it definitely did not disappear in a fire.

**Comment by acikek** [comment]
Can you send a log?

**Comment by redstonekasi** [comment]
Sorry I can't provide any logs, I may have an idea as to what caused the first issue though, I have a hole in my end island that leads directly to the void, if the selected position is above void the item isn't spawned. Though this would be more of an issue for Void Crafting than Purpeille.

**Comment by acikek** [comment]
This is intentional. If a valid solid block isn't found at the chosen radius, the recipe doesn't go through. It works at any height, however, so if you make a 10-15 block wide platform at the max height in the center of your end island, it'll spawn there.

**Comment by redstonekasi** [comment]
Thought so. I believe the occurrence in the Nether might have actually been fire so I'll close the issue now.
