### ISSUE TITLE
Crash with AdvancementInfo

### ISSUE THREAD

**Issue by Fourbo** [acikek/purpeille#5]
I was testing my modpack, and when I tried to open the Purpeille advancement tab, my game crashed, and Not Enough Crashes reported that the issues arose from AdvancmentInfo and Purpeille. When I turned off the AdvancementInfo mod, the Purpeille advancement tab worked just fine and there was no crash.
Fabric Loader: 0.14.6
Fabric API: 0.55.1

Here is the link to the crash report:
https://gist.github.com/Fourbo/3ed3ef02a1dc8358a6f54b1e3cfb10af

**Comment by acikek** [comment]
Looks like I just forgot some null checks. Fix will be out later today along with another update.

**Comment by acikek** [comment]
Fixed in version 2.3.1. Have fun!
