### ISSUE TITLE
Poison resistance mixin prevents further processing of poison logic by other mods

### ISSUE THREAD

**Issue by SilverAndro** [acikek/purpeille#8]
This came up over discord from someone using RPGStats, because you fast cancel status effects on poison, the lv25 effect for rpgstats which is supposed to make you immune to poison never runs. https://github.com/acikek/purpeille/blob/fabric-1.19/src/main/java/com/acikek/purpeille/mixin/StatusEffectMixin.java

I think we both need to modify our mixins to use modifyarg on the damage call here? Im fairly sure that one is chainable which should allow our logic to work in tandem

**Comment by acikek** [comment]
Hmm, nice catch. I'll see what I can do tonight if I have time. Is there any reasonable way to test compatibility though?

**Comment by SilverAndro** [comment]
Im working on pushing a version that should have a more compatible mixin rn, once thats out can just throw them together, `/rpgcheat` yourself magic 50 or something, and see if poison effects you or not.

**Comment by SilverAndro** [comment]
Published, should be good to test against

https://modrinth.com/mod/rpgstats/version/4.4.1
https://github.com/SilverAndro/RPGStats/commit/9ef4576c59e727ac701c737ebbda05558652b70e

**Comment by acikek** [comment]
[Try this alpha version](https://modrinth.com/mod/purpeille/version/3.2.1-alpha.1%2Bfabric-1.19)
718818c1437eeeeb01ecae9cd4a4b948ef771b13 (kinda stole your code)

Tested in singleplayer. When player has magic 50, poison is negated, even when they're holding a Malaise item.

**Comment by SilverAndro** [comment]
Yep seems to be working for me as well, very cool!

And yeah that's why I linked it haha, figured it might be helpful, thanks much!

**Comment by acikek** [comment]
[Released in 3.2.1](https://modrinth.com/mod/purpeille/version/3.2.1%2Bfabric-1.19)
