### ISSUE TITLE
[QUILT 1.19.2] Poison Immunity always applies, even without an item that grants it.

### ISSUE THREAD

**Issue by f-raZ0R** [acikek/purpeille#9]
I have isolated this problem to happening with just Purpeille, and no other mods. You are completely immune to poison damage, even without any items.

Expected behavior:
-You are only immune to Poison Damage with an item that grants poison immunity.

Actual behavior:
-You are always immune to Poison Damage.

**Comment by f-raZ0R** [comment]
Fixed in 3.2.2

**Comment by acikek** [comment]
Sorry for not replying to this sooner, I had a busy day yesterday. You're correct. 3.2.2 fixes this and I'll publicly announce it shortly

By the way, the commit that fixed it modified two characters... whoops
